### ISSUE TITLE
Add share post feature

### ISSUE THREAD

**Issue by amitness** [iKevinY/pneumatic#5]
I found this plugin: https://github.com/getpelican/pelican-plugins/tree/master/share_post to add social share buttons to the site without using any JS. It's minimal.

I've implemented it in a fork for pneumatic. Please have a look: https://amitness.com/2015/06/ubuntu-keyboard-shortcut/

Is it OK to send you a PR?

**Comment by iKevinY** [comment]
Glad to see you're using Pneumatic, @amitness! I'd like to keep the theme as light as possible (the fact that it already requires installing two plugins is slightly undesirable), so while I agree that your share buttons are minimal, I don't think I'll merge it into the main repo.
