### ISSUE TITLE
Error in using Pelican 4

### ISSUE THREAD

**Issue by bergpb** [iKevinY/pneumatic#7]
After add a theme in my pelicanconf.py and run with make devserver, show this error in terminal:
`Caught exception "TemplateSyntaxError: Encountered unknown tag 'assets'.". Reloading.`
Can help me to install?

**Comment by iKevinY** [comment]
Hi @bergpb! I tested my blog's deploy on Pelican 4 and it seems fine. You need to make sure the [`assets`](https://github.com/getpelican/pelican-plugins/tree/master/assets) plugin is installed, and make sure your [configuration file correctly imports that plugin](https://github.com/iKevinY/iKevinY.github.io/blob/db67498c819118eb9cabd326c7118aa10c7798c3/pelicanconf.py#L86).

**Comment by bergpb** [comment]
Hello @iKevinY, i try this and works, but after install sass i get this error, can you help me ?

Modified: content, settings, theme, [static]images. re-generating...
WARNING: Caught exception "FilterError: scss: subprocess returned a non-success result code: 64, stdout=b'Could not find an option named "line-comments".\n\nUsage: sass <input.scss> [output.css]\n       sass <input.scss>:<output.css> <input/>:<output/>\n\n\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81 Input and Output \xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\n    --[no-]stdin               Read the stylesheet from stdin.\n    --[no-]indented            Use the indented syntax for input from stdin.\n-I, --load-path=<PATH>         A path to use when resolving imports.\n                               May be passed multiple times.\n\n-s, --style=<NAME>             Output style.\n                               [expanded (default), compressed]\n\n    --update                   Only compile out-of-date stylesheets.\n\n\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81 Source Maps \xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\n    --[no-]source-map          Whether to generate source maps.\n                               (defaults to on)\n\n    --source-map-urls          How to link from source maps to source files.\n                               [relative (default), absolute]\n\n    --[no-]embed-sources       Embed source file contents in source maps.\n    --[no-]embed-source-map    Embed source map contents in CSS.\n\n\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81 Other \xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\xe2\x94\x81\n    --watch                    Watch stylesheets and recompile when they change.\n    --[no-]poll                Manually check for changes rather than using a native watcher.\n                               Only valid with --watch.\n\n    --[no-]stop-on-error       Don\'t compile more files once an error is encountered.\n-i, --interactive              Run an interactive SassScript shell.\n-c, --[no-]color               Whether to emit terminal colors.\n-q, --[no-]quiet               Don\'t print warnings.\n    --[no-]trace               Print full Dart stack traces for exceptions.\n-h, --help                     Print this usage information.\n    --version                  Print the version of Dart Sass.\n', stderr=b''". Reloading.

**Comment by iKevinY** [comment]
@bergpb I also get that error when I try using the latest version of Sass, but I haven't had the time to look into why. If you install Sass 3.4.25 specifically (`gem install sass -v 3.4.25`) it should work (that's the version I use to build my website currently).

**Comment by bergpb** [comment]
I'm install sass with npm and return this error,  after install with gem working fine. Thanks for your help.
👍 👍

**Comment by jerpint** [comment]
Hi, I am getting a similar issue using sass installed directly by pointing my $PATH to the folder, any idea how to solve this? I have added the line-content related snippet as per the README in `pelicanconf.py`

```
$ pelican content
CRITICAL: FilterError: scss: subprocess returned a non-success result code: 64, stdout=Could not find an option named "line-comments".
  |
  | Usage: sass <input.scss> [output.css]
  |        sass <input.scss>:<output.css> <input/>:<output/> <dir/>
```

**Comment by iKevinY** [comment]
@jerpint I remember running into some issues with the newer (non-gem) version of `sass`; I'm not sure if this error was the problem specifically, but for my CI build I force-install a [specific version of `sass`](https://github.com/iKevinY/iKevinY.github.io/blob/ea5f71ccf3fe154e6929485b3715949e80b750ba/Makefile#L14). Let me know if this fixes the issue.

**Comment by frapac** [comment]
The issue seems fixed with `sass 3.7` (by installing `sass` with the system package manager: `pacman -S ruby-sass`).

**Comment by 1oglop1** [comment]
@frapac This shouldn't be a solution.
I found this at ruby sass website
```
Ruby Sass was the original implementation of Sass, but it reached its end of life as of 26 March 2019. It's no longer supported, and Ruby Sass users should migrate to another implementation.
```

**Comment by frapac** [comment]
Oh, I didn't know that... Thanks for the update!
